version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: /main
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./ddl/:/docker-entrypoint-initdb.d/
